# Generated by Django 6.0.4 on 2026-05-14 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisreport",
            name="is_deleted_by_user",
            field=models.BooleanField(default=False),
        ),
    ]
