# Generated by Django 6.0.4 on 2026-05-14 01:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_analysisreport_is_deleted_by_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DermatologistSuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "suggestion_type",
                    models.CharField(
                        choices=[
                            ("recommended", "Highly Recommended"),
                            ("caution", "Use with Caution"),
                            ("avoid", "Avoid"),
                            ("consult", "Consult Dermatologist"),
                        ],
                        max_length=50,
                    ),
                ),
                ("suggestion_text", models.TextField()),
                ("dermatologist_name", models.CharField(blank=True, max_length=200)),
                ("credentials", models.CharField(blank=True, max_length=200)),
                ("reference_link", models.URLField(blank=True)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dermatologist_suggestions",
                        to="core.ingredient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ScientificApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approval_level",
                    models.CharField(
                        choices=[
                            ("fda", "FDA Approved"),
                            ("eu", "EU Approved"),
                            ("dermatologist", "Dermatologist Recommended"),
                            ("clinical", "Clinically Proven"),
                            ("research", "Peer-Reviewed Research"),
                            ("pending", "Pending Approval"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("approval_number", models.CharField(blank=True, max_length=100)),
                ("approval_date", models.DateField(blank=True, null=True)),
                (
                    "research_papers",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated research paper links or citations",
                    ),
                ),
                (
                    "clinical_studies",
                    models.TextField(blank=True, help_text="Clinical study references"),
                ),
                ("certifying_body", models.CharField(blank=True, max_length=200)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                (
                    "ingredient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scientific_approval",
                        to="core.ingredient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SkinAnalysisReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=200)),
                (
                    "user_skin_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("oily", "Oily Skin"),
                            ("dry", "Dry Skin"),
                            ("combination", "Combination Skin"),
                            ("normal", "Normal Skin"),
                            ("sensitive", "Sensitive Skin"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("ingredients_analyzed", models.JSONField(default=list)),
                (
                    "overall_score",
                    models.IntegerField(
                        default=0, help_text="0-100 overall product score"
                    ),
                ),
                (
                    "skin_compatibility_score",
                    models.IntegerField(
                        default=0, help_text="0-100 compatibility with user's skin"
                    ),
                ),
                ("safety_score", models.IntegerField(default=0)),
                ("efficacy_score", models.IntegerField(default=0)),
                ("safe_count", models.IntegerField(default=0)),
                ("moderate_count", models.IntegerField(default=0)),
                ("harmful_count", models.IntegerField(default=0)),
                ("scientifically_approved_count", models.IntegerField(default=0)),
                ("dermatologist_recommended_count", models.IntegerField(default=0)),
                (
                    "overall_verdict",
                    models.CharField(
                        choices=[
                            ("excellent", "Excellent Choice 🌟"),
                            ("good", "Good Choice ✅"),
                            ("moderate", "Use with Caution ⚠️"),
                            ("avoid", "Avoid ❌"),
                        ],
                        default="moderate",
                        max_length=50,
                    ),
                ),
                ("recommendation_summary", models.TextField()),
                ("skin_specific_advice", models.TextField(blank=True)),
                ("alternatives_suggested", models.JSONField(blank=True, default=list)),
                ("analyzed_at", models.DateTimeField(auto_now_add=True)),
                ("is_deleted_by_user", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-analyzed_at"],
            },
        ),
        migrations.CreateModel(
            name="UserSkinProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skin_type",
                    models.CharField(
                        choices=[
                            ("oily", "Oily Skin"),
                            ("dry", "Dry Skin"),
                            ("combination", "Combination Skin"),
                            ("normal", "Normal Skin"),
                            ("sensitive", "Sensitive Skin"),
                        ],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "skin_concerns",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="e.g., ['acne', 'aging', 'dryness']",
                    ),
                ),
                ("allergies", models.JSONField(blank=True, default=list)),
                ("current_routine", models.JSONField(blank=True, default=list)),
                ("preferred_textures", models.JSONField(blank=True, default=list)),
                ("budget_range", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SkinTypeRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "skin_type",
                    models.CharField(
                        choices=[
                            ("oily", "Oily Skin"),
                            ("dry", "Dry Skin"),
                            ("combination", "Combination Skin"),
                            ("normal", "Normal Skin"),
                            ("sensitive", "Sensitive Skin"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "suitability_score",
                    models.IntegerField(default=50, help_text="0-100 score"),
                ),
                ("recommendation_text", models.TextField(blank=True)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skin_recommendations",
                        to="core.ingredient",
                    ),
                ),
            ],
            options={
                "unique_together": {("ingredient", "skin_type")},
            },
        ),
    ]
